### ISSUE TITLE
Missing Ontology

### ISSUE THREAD

**Issue by cehberlin** [frovida/skiros#1]
It seems like the OWL reference is broken:

http://www.semanticweb.org/francesco/ontologies/2014/9/stamina gives 404 error.

For this reason I am not able to execute 
roslaunch skiros skiros_system.launch

**Comment by frovida** [comment]
Hi Christopher,
I need more info to debug this. Are you using master branch or indigo branch? Can you run the launch in debug mode (debug:=true) and tell me the error msg appearing on the world model node?

**Comment by cehberlin** [comment]
Hi frovida,
thanks for the fast response. I have used your master branch on ROS Kinetic (Ubuntu 16.04).

After a successful compilation I run `roslaunch skiros skiros_system.launch debug:=true`:
and get following output. 

```
started roslaunch server http://dai076:39431/

SUMMARY
========

PARAMETERS
 * /aau_stamina_robot/module_list: 
 * /aau_stamina_robot/skill_list: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /skiros/owl_workspace: /home/toffer/Dev/...
 * /skiros/save_log: False
 * /skiros/scene_name: fake_scene.xml
 * /skiros/scene_workspace: /home/toffer/Dev/...

NODES
  /
    aau_stamina_robot (skiros_skill/skill_manager_node)
    skiros_gui (rqt_gui/rqt_gui)
    skiros_task_manager (skiros_task/task_manager_node)
    skiros_wm (skiros_world_model/world_model_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[skiros_wm-1]: started with pid [28932]
process[skiros_task_manager-2]: started with pid [28933]
process[skiros_gui-3]: started with pid [28934]
process[aau_stamina_robot-4]: started with pid [28935]
[ WARN] [1506338256.469498951]: [WorldModelInterface] The world model is not connected.
[ WARN] [1506338256.470350498]: [SkirosGui::initPlugin] World model seems down, waiting...
[ WARN] [1506338259.504661057]: [SkirosGui::initPlugin] World model seems down, waiting...
[ INFO] [1506338259.504832621]: [SkirosGui::initPlugin] Connected to world model
[ WARN] [1506338260.005970376]: [WorldModelInterface] The world model is not connected.
RosPluginlibPluginProvider::load_explicit_type(skiros_gui/Skiros) failed initializing plugin ([WorldModelInterface::query] ROS connection to world model failed.)
PluginManager._load_plugin() could not load plugin "skiros_gui/Skiros": RosPluginlibPluginProvider.load() could not load plugin "skiros_gui/Skiros"
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Das Argument ist ungültig
[skiros_gui-3] process has died [pid 28934, exit code -6, cmd /opt/ros/kinetic/lib/rqt_gui/rqt_gui -s skiros __name:=skiros_gui __log:=/home/toffer/.ros/log/4bd498b6-a1e2-11e7-8e02-28d2442e159c/skiros_gui-3.log].
log file: /home/toffer/.ros/log/4bd498b6-a1e2-11e7-8e02-28d2442e159c/skiros_gui-3*.log
```

I somewhere discovered above OWL reference and tested it in a browser, where the link seemed broken. Therefore, I posted above issue.

**Comment by frovida** [comment]
I'm sorry, but from this I can't still see the wold model output, you should copy the output of the world model node (it is opened in a separate window). 

Anyhow, the ontology file is not on the web, it is located in the folder skiros/owl. I don't think is that the problem (but I can't be sure without seeing the log)

Maybe try to download also the skiros_std_lib and use the launch file provided in there

**Comment by pannedgun** [comment]
I think I'm currently facing the same problem. Launching the whole system through roslaunch skiros skiros_system.launch or the launch from skiros_std_lib causes the world_model_node to crash even though launching it seperately works.
gdb produces:
`[ INFO] [1506417219.513018040]: [loadMainOntology]: I add: rdf - http://www.w3.org/1999/02/22-rdf-syntax-ns
[ INFO] [1506417219.513081419]: [loadMainOntology]: I add: owl - http://www.w3.org/2002/07/owl
[ INFO] [1506417219.513096708]: [loadMainOntology]: I add: xml - http://www.w3.org/XML/1998/namespac
[ INFO] [1506417219.513109690]: [loadMainOntology]: I add: voag - http://voag.linkedmodel.org/schema/voag
[ INFO] [1506417219.513140407]: [loadMainOntology]: I add: xsd - http://www.w3.org/2001/XMLSchema
[ INFO] [1506417219.513160934]: [loadMainOntology]: I add: rdfs - http://www.w3.org/2000/01/rdf-schema
[ INFO] [1506417219.513217942]: [loadMainOntology]: I add: http://www.semanticweb.org/francesco/ontologies/2014/9/stamina
[ INFO] [1506417219.688794955]: Main ontology: /home/alex/skiros/src/skiros/skiros/owl/stamina.owl, loaded successfully.
[ INFO] [1506417219.689073049]: [loadSubOntology]: I add: http://www.semanticweb.org/francesco/ontologies/2014/9/stamina
[ INFO] [1506417219.689357806]: Sub ontology: /home/alex/skiros/src/skiros/skiros/owl/learned_concepts.owl, loaded successfully.
[ INFO] [1506417219.690813753]: Opening file '/home/alex/skiros/src/skiros/skiros/scenes/fake_scene.xml'...
world_model_node: /home/alex/skiros/src/skiros/skiros_common/include/skiros_common/serializable_any.h:163: static const std::type_info& skiros_common::any::getTypeFromHash(uint64_t): Assertion `i != map.end()' failed.

Thread 1 "world_model_nod" received signal SIGABRT, Aborted.
0x00007ffff4892428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
`

**Comment by alex94263** [comment]
I think I'm currently facing the same problem. Launching the whole system through roslaunch skiros skiros_system.launch or the launch in skiros_std_lib seems to crash the world_model_node, while launching the nodes seperately or through skiros_task_and_wm.launch and skiros_skill_mgr.launch works.
starting the whole system in debug mode, gdb produces the following error msgs:
```
Starting program: /home/alex/skiros/devel/lib/skiros_world_model/world_model_node __name:=skiros_wm __log:=/home/alex/.ros/log/fb21f9f4-a29a-11e7-bb21-48e244a25f7b/skiros_wm-2.log
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8ccc700 (LWP 21666)]
[New Thread 0x7fffe3fff700 (LWP 21667)]
[New Thread 0x7fffe37fe700 (LWP 21668)]
[New Thread 0x7fffe2ffd700 (LWP 21673)]
[New Thread 0x7fffe216c700 (LWP 21950)]
[New Thread 0x7fffe196b700 (LWP 21951)]
[New Thread 0x7fffe116a700 (LWP 21952)]
[ INFO] [1506417219.513018040]: [loadMainOntology]: I add: rdf - http://www.w3.org/1999/02/22-rdf-syntax-ns
[ INFO] [1506417219.513081419]: [loadMainOntology]: I add: owl - http://www.w3.org/2002/07/owl
[ INFO] [1506417219.513096708]: [loadMainOntology]: I add: xml - http://www.w3.org/XML/1998/namespac
[ INFO] [1506417219.513109690]: [loadMainOntology]: I add: voag - http://voag.linkedmodel.org/schema/voag
[ INFO] [1506417219.513140407]: [loadMainOntology]: I add: xsd - http://www.w3.org/2001/XMLSchema
[ INFO] [1506417219.513160934]: [loadMainOntology]: I add: rdfs - http://www.w3.org/2000/01/rdf-schema
[ INFO] [1506417219.513217942]: [loadMainOntology]: I add: http://www.semanticweb.org/francesco/ontologies/2014/9/stamina
[ INFO] [1506417219.688794955]: Main ontology: /home/alex/skiros/src/skiros/skiros/owl/stamina.owl, loaded successfully.
[ INFO] [1506417219.689073049]: [loadSubOntology]: I add: http://www.semanticweb.org/francesco/ontologies/2014/9/stamina
[ INFO] [1506417219.689357806]: Sub ontology: /home/alex/skiros/src/skiros/skiros/owl/learned_concepts.owl, loaded successfully.
[ INFO] [1506417219.690813753]: Opening file '/home/alex/skiros/src/skiros/skiros/scenes/fake_scene.xml'...
world_model_node: /home/alex/skiros/src/skiros/skiros_common/include/skiros_common/serializable_any.h:163: static const std::type_info& skiros_common::any::getTypeFromHash(uint64_t): Assertion `i != map.end()' failed.

Thread 1 "world_model_nod" received signal SIGABRT, Aborted.
0x00007ffff4892428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
```

**Comment by frovida** [comment]
Thanks for the feedback alex. It was the scene that was somehow corrupted.

The problem should be fixed now.
